function initVars()
{
	variables['dynamic_instruction_count']="9";	//Number of dynamic instructions
	variables['dynamic_instruction_image_1']="robber2.png";	//dynamic instruction image 1
	variables['dynamic_instruction_image_2']="police.png";	//dynamic instruction image 2
	variables['dynamic_instruction_image_3']="";	//dynamic instruction image 3
	variables['dynamic_instruction_image_4']="";	//dynamic instruction image 4
	variables['dynamic_instruction_image_5']="";	//dynamic instruction image 5
	variables['dynamic_instruction_image_6']="";	//dynamic instruction image 6
	variables['dynamic_instruction_image_7']="considering.png";	//dynamic instruction image 7
	variables['dynamic_instruction_image_8']="justice.png";	//dynamic instruction image 8
	variables['dynamic_instruction_image_9']="judge.png";	//dynamic instruction image 9
	variables['dynamic_instruction_text_1']="You and other players are partners in a bank robbery ring. After robbing %total_rounds_count% banks, you have both been arrested by the police.";	//dynamic instruction 1 text 
	variables['dynamic_instruction_text_2']="At the start of this process, neither you nor your partner have said anything to the police. The police do not have enough evidence to convict both of you for all the robberies, so you will be sentenced on a lesser charge of trespassing for each of %total_rounds_count% counts.";
	variables['dynamic_instruction_text_3']="As long as neither you nor your partner testify, you will each receive a sentence of %payoff[2][2]% years for each count. Go on and press on Don't Testify...";
	variables['dynamic_instruction_text_4']="The prosecutor walks in and offers you a deal on the first count. If you testify against your partner and your partner does not testify against you, you will get %payoff[1][2]% years in prison and your partner will get %payoff[2][1]% years in prison. Go on and press on Testify...";
	variables['dynamic_instruction_text_5']="But if your partner testifies against you and you do not testify against your partner, you will get %payoff[2][1]% years in prison and your partner will get %payoff[1][2]% years in prison. Observe this behavior by pressing on Don't Testify...";
	variables['dynamic_instruction_text_6']="Finally, if you both end up testifying against each other, you both end up %payoff[1][1]% years in prison. Go on and press on Testify...";
	variables['dynamic_instruction_text_7']="You are being held in seperate rooms and there is no way of exchanging messages with each other. You obviously want to minimize the time you spend in jail but you and your partner only have the options of testifying against the other or not testfying against the other for each the %total_rounds_count% rounds of crimes.";
	variables['dynamic_instruction_text_8']="After you and your partner both make your choices, the prosecutor will tell you the resulting sentence for that count. Based on the sentences that you each get, you each will know whether or not the other one testified.";
	variables['dynamic_instruction_text_9']="Then the same process begins again for each of the remaining counts.";
	variables['dynamic_instruction_text_1_payoff_cell']="";	//Pay off cell for dynamic instruction text 1 which is being introduced 
	variables['dynamic_instruction_text_2_payoff_cell']="";
	variables['dynamic_instruction_text_3_payoff_cell']="(2,2)";
	variables['dynamic_instruction_text_4_payoff_cell']="(1,2)";
	variables['dynamic_instruction_text_5_payoff_cell']="(2,1)";
	variables['dynamic_instruction_text_6_payoff_cell']="(1,1)";
	variables['dynamic_instruction_text_7_payoff_cell']="";
	variables['dynamic_instruction_text_8_payoff_cell']="";
	variables['dynamic_instruction_text_9_payoff_cell']="";
	variables['information_column_count']="2";	//Number of information columns 
	variables['information_row1_column1_image']="neither_acuse.png";	//information row 1 column 1 image 
	variables['information_row1_column1_outcome_text']="None of you ended up testifying, you will get %payoff[2][2]% years in prison.";	//information row 1 column 1 outcome text
	variables['information_row1_column1_payoff_cells']="(2,2)";	//Payoff cells for row 1 column 1
	variables['information_row1_column1_text']="If neither of you end up testifying, you'll both get %payoff[2][2]% years in prison.";	//information row 1 column 1 text
	variables['information_row1_column2_image']="purple-acuse.png";	
	variables['information_row1_column2_outcome_text']="You did not testify against your partner but he or she testified against you, you will get %payoff[2][1]% years in prison.";	
	variables['information_row1_column2_payoff_cells']="(2,1)";	
	variables['information_row1_column2_text']="If you don't testify against you your partner but he or she testifies against you, you'll get %payoff[2][1]% years in prison.";	
	variables['information_row2_column1_image']="blue-acuse.png";	
	variables['information_row2_column1_outcome_text']="You testified against your partner before him/her, you'll get %payoff[1][2]% years in prison.";	
	variables['information_row2_column1_payoff_cells']="(1,2)";	
	variables['information_row2_column1_text']="If you testify against your partner before he or she testifies against you, you'll get %payoff[1][2]% years in prison.";	
	variables['information_row2_column2_image']="both-acuse.png";	
	variables['information_row2_column2_outcome_text']="Both of you testified against each other, you will both get %payoff[1][1]% years in prison.";	
	variables['information_row2_column2_payoff_cells']="(1,1)";	
	variables['information_row2_column2_text']="If you both testify against each other, you both get %payoff[1][1]% years in prison.";	
	variables['information_row_count']="2";	//Number of information rows 
	variables['Polling_Text']="You are not currently assigned to a round. Please wait...";	//Text that is displayed if you aren't included in a round 
	variables['Prev_Rnd_Choice_Text']="Prev. Round Choice";	//Previous round choice caption
	variables['Prev_Rnd_Payoff_Text']="Prev. Round Payoff";	//Previous round payoff caption
	variables['static_instruction_count']="9";	//Number of static instructions
	variables['static_instruction_image_1']="robber2.png";	//static instruction 1 image
	variables['static_instruction_image_2']="police.png";
	variables['static_instruction_image_3']="celebrate.png";
	variables['static_instruction_image_4']="trip.png";
	variables['static_instruction_image_5']="chains2.png";
	variables['static_instruction_image_6']="pointing.png";
	variables['static_instruction_image_7']="considering.png";
	variables['static_instruction_image_8']="justice.png";
	variables['static_instruction_image_9']="judge.png";
	variables['static_instruction_text_1']="You and other players are partners in a bank robbery ring. After robbing %total_rounds_count% banks, you have both been arrested by the police.";	//static instruction 1 text 
	variables['static_instruction_text_2']="At the start of this process, neither you nor your partner have said anything to the police. The police do not have enough evidence to convict both of you for all the robberies, so you will be sentenced on a lesser charge of trespassing for each of %total_rounds_count% counts.";
	variables['static_instruction_text_3']="As long as neither you nor your partner testify, you will each receive a sentence of %payoff[2][2]% years for each count.";
	variables['static_instruction_text_4']="The prosecutor walks in and offers you a deal on the first count. If you testify against your partner and your partner does not testify against you, you will get %payoff[1][2]% years in prison and your partner will get %payoff[2][1]% years in prison.";
	variables['static_instruction_text_5']="But if your partner testifies against you and you do not testify against your partner, you will get %payoff[2][1]% years in prison and your partner will get %payoff[1][2]% years in prison.";
	variables['static_instruction_text_6']="Finally, if you both end up testifying against each other, you both end up %payoff[1][1]% years in prison.";
	variables['static_instruction_text_7']="You are being held in seperate rooms and there is no way of exchanging messages with each other. You obviously want to minimize the time you spend in jail but you and your partner only have the options of testifying against the other or not testfying against the other for each the %total_rounds_count% rounds of crimes.";
	variables['static_instruction_text_8']="After you and your partner both make your choices, the prosecutor will tell you the resulting sentence for that count. Based on the sentences that you each get, you each will know whether or not the other one testified.";
	variables['static_instruction_text_9']="Then the same process begins again for each of the remaining counts.";
	variables['Total_Payoff_Text']="Total Jail Time";	//Total Payoff 
	variables['Your_Choice_Text']="You selected ";	//Text that is displayed when a choice is selected 
	variables['Avg_Payoff_Text']="Average Payoff";	//Average payoff text
}